### ISSUE TITLE
can't upload resign ipa to app store

### ISSUE THREAD

**Issue by BruceTseng** [InjoyDeng/ResignTool#1]
when I upload the ipa to app store via application loader, it will show below error message

ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value XXXXXXXX.com.xxx.xxx.xx for key 'application-identifier' in 'Payload/Guidebook.app/Frameworks/AFNetworking.framework/AFNetworking' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."

**Comment by InjoyDeng** [comment]
I'm sorry to hear you're facing the issue. 

I think this is because 'application-identifier' is not set to the correct value, so the solution was to change application-identifier specifying the correct application bundle ID inside Entitlements.plist.
